# Generated by Django 3.0.3 on 2020-02-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bballModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AddField(
            model_name='team',
            name='PythW',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='RPI',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='SOS',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='aa',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='ab',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='afbp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='aorb',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='apa',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='apd',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='apip',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='aps',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='ascp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='at',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='avgs',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='awayWP',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='awp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='blkp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='dm',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='drtg',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='efg',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='erb',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='fgp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='ftp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='ftr',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='last10',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='nonConf',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='nrtg',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='oowp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='orb',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='ortg',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='owp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='pace',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='teamID',
            field=models.CharField(default=None, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='team',
            name='threepp',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='top25',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='tovr',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='ts',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='team',
            name='wp',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
