# Generated by Django 3.0.3 on 2020-02-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bballModel', '0002_auto_20200212_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='lineNumber',
            field=models.IntegerField(default=0),
        ),
    ]
