# Generated by Django 3.0.3 on 2020-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bballModel', '0003_team_linenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='lineNumber',
            field=models.IntegerField(),
        ),
    ]
